[project]
name = "hexlet-code"  # Имя проекта
version = "0.1.0"  # Версия
description = "A package to compare files"  # Описание
authors = [
    {name = "RatiborM", email = "r_morkvin@vk.com"}
]

dependencies = []

[tool.uv.dependencies]
python = "^3.10"

[tool.uv.scripts]
mygendiff  = "gendiff.scripts.gendiff:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["gendiff"]