[project]
name = "hexlet-code"
version = "0.1.0"
description = "A package to compare files"
authors = [
    {name = "RatiborM", email = "r_morkvin@vk.com"}
]

[tool.poetry]
name = "python-project-50"
version = "0.1.0"
description = "Вычислитель отличий"
authors = ["Роман Морквин <r_morkvin@.com>"]

[tool.poetry.dependencies]
python = "^3.10"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
flake8 = "^6.1.0"

[tool.poetry.scripts]
gendiff = "gendiff.scripts.gendiff:main"

[tool.poetry.group.dev.dependencies]
flake8 = "6.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"