[project]
name = "hexlet-code"
version = "0.1.0"
description = "A package for comparing configuration files"
authors = [
    {name = "RatiborM", email = "r_morkvin@vk.com"}
]
requires-python = ">=3.10"

dependencies = [
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0"
]

[project.scripts]
gendiff = "gendiff.scripts.gendiff:main"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"