[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = "A package for comparing configuration files"
authors = ["RatiborM <r_morkvin@vk.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pyyaml = "^6.0"
pytest = "^8.3.4"
pytest-cov = "^6.0.0"

[tool.poetry.scripts]
gendiff = "gendiff.scripts.gendiff:main"

[project]
requires-python = ">=3.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
